name: Build and push Docker on merging

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          docker build . -t nsignori/osrs-discord-bot:latest
          docker push nsignori/osrs-discord-bot:latest
      - name: Portainer Stack Redeploy
        uses: zzzze/webhook-trigger@v1.0.0
        with:
          webhook_url: https://docker.woofi7.com/api/stacks/webhooks/9d71546e-74fe-4aea-9fcb-bcc4fc2aead6
